### ISSUE TITLE
get() fails when archived filter uses default value

### ISSUE THREAD

**Issue by gianklug** [adfinis/libtimed#10]
```py
Traceback (most recent call last):
  File "/home/giank/git/timedctl/timedctl/timedctl.py", line 556, in <module>
    timedctl()
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/git/timedctl/timedctl/timedctl.py", line 331, in add_report
    customers = timed.customers.get()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/libtimed/models.py", line 122, in get
    params = {**self._parse_filters(filters), "include": include}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/libtimed/models.py", line 173, in _parse_filters
    return {
           ^
  File "/home/giank/.local/lib/python3.11/site-packages/libtimed/models.py", line 174, in <dictcomp>
    name: (transform).serialize(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giank/.local/lib/python3.11/site-packages/libtimed/transforms.py", line 45, in serialize
    return self.pipe(a)
           ^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

NoneType can't be casted into an integer obviously.

**Comment by gianklug** [comment]
Fixed in https://github.com/adfinis/libtimed/commit/21a396dd57c0a47bfa8f65d1aff1357cad387074
